[package]
name = "cluster-controller"
version = "0.1.0"
authors = ["Esa Varemo <esa@kuivanto.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k8s-openapi = { version = "0.10.0", default-features = false, features = ["v1_19"] }
kube = { git = "https://github.com/clux/kube-rs", rev = "f49fcc4b64ca53091efe15f570e38c6ab3789567" }
kube-runtime = { git = "https://github.com/clux/kube-rs", rev = "f49fcc4b64ca53091efe15f570e38c6ab3789567" }

serde = "1.0.117"
serde_json = "1.0.59"
serde_derive = "1.0.117"

tokio = { version = "0.2.3", features = ["full"] }
tempfile = "3.1.0"
futures = "0.3.5"
