apiVersion: cluster-virt.acl.fi/v1beta2
kind: VirtualMachine
metadata:
  name: vm-1.mydomain.com
  namespace: test
spec:
  cpus: 3
  memory: 2G
  volumes:
    - name: vm-1-root
  networks:
    - name: testnet
