FROM rust:1.98.1-bookworm

RUN <<EOF
    set -eu

    apt-get update
    apt-get install -y --no-install-recommends \
      build-essential git clang llvm libclang-dev librados-dev \
      librbd-dev libvirt-dev pkg-config libssl-dev openssl ca-certificates curl \
      ovn-central openvswitch-common
EOF